<a href="https://colab.research.google.com/github/Sak-shi437/deep_learning/blob/main/Pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


In [5]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


**Introduction to Tensors**

creating Tensors


In [6]:
#Scaler

scalar = torch.tensor(7)
scalar


tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as python int
scalar.item()

7

In [9]:
#vector

vector = torch.tensor([7,7])
vector
vector.ndim


1

In [10]:
vector.shape

torch.Size([2])

**matrix**

In [11]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

**tesors**

In [14]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# Create a rondom tensor with similar shape to an image tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0151, 0.4153, 0.8705, 0.5921],
        [0.2502, 0.5076, 0.7234, 0.8883],
        [0.1150, 0.8890, 0.2828, 0.1685]])

In [19]:


# Create a random tensor with similar shape to an image tensor

radom_image_size = torch.rand(size=(224,224,3))
radom_image_size.shape,radom_image_size.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and **Ones**

In [20]:
# Create a tensor of all zeros

Zeros = torch.zeros(size=(3,4))
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-**like**

In [6]:
# Use torch.range() and get deprecated message, use torch.arange()

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes
Note:

 Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

Tensors not right datatype
Tensors not right shape
Tensors not on the right device
Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.



In [ ]:
# Float 32 tensor
